### ISSUE TITLE
Include important features 

### ISSUE THREAD

**Issue by khalifa005** [iammukeshm/AspNetCoreHero-Boilerplate#1]
1-Send mail 
2- exception middle ware and logging   
3- localization with portable object or resources file 
4- LTR - RTL

**Comment by iammukeshm** [comment]
Yes, all these features will be included. Thanks for mentioning though

**Comment by khalifa005** [comment]
No thanks to you for your great effort a awesome articles

**Comment by iammukeshm** [comment]
Here is a small demonstration of the RTL and Multilingual Feature. 
https://www.facebook.com/codewithmukesh/posts/170554741308969

**Comment by mahmudkhalifa** [comment]
Wonderful i can't wait to complete this awesome template @iammukeshm   👍
