### ISSUE TITLE
New User Create Required from Super User

### ISSUE THREAD

**Issue by next-pixel** [iammukeshm/AspNetCoreHero-Boilerplate#4]
Required New user create Feature from Super admin

Thanks

**Comment by iammukeshm** [comment]
![chrome_Tou1kTqgoh](https://user-images.githubusercontent.com/31455818/95371925-7bfcaa80-08f8-11eb-911f-f5c928d14e5e.jpg)
![chrome_XDN9jVpXBx](https://user-images.githubusercontent.com/31455818/95371930-7dc66e00-08f8-11eb-8eca-e91e60c04498.jpg)
Thanks for the suggestion! It's added along with both client / server side validation. Kindly let me know your feedback . I am also attaching the screenshots.
